name: Laravel CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          coverage: pcov

      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Update Dependencies
        run: composer update

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update .env for SQLite
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env

      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Display .env file
        run: cat .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests with phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
